// Bindings not present in wrangler.jsonc (secrets, optional vars) merged into
// the Env interface generated by `wrangler types`.
interface Env {
  /**
   * Optional fallback seats.aero Partner API key for private single-user
   * deployments (`wrangler secret put SEATS_AERO_API_KEY`). Normally callers
   * supply their own key per-request via the X-Seats-Aero-Api-Key header.
   */
  SEATS_AERO_API_KEY?: string;
  /** Zero Trust team domain (e.g. "myteam"). Set with ACCESS_APP_AUD to enforce Access JWT validation. */
  ACCESS_TEAM_DOMAIN?: string;
  /** Audience (AUD) tag of the Cloudflare Access application protecting this Worker. */
  ACCESS_APP_AUD?: string;
}
